apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: gohello
    skaffold.dev/tail: "true"
  name: gohello
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8080
  selector:
    app: gohello
  sessionAffinity: None
  type: NodePort
