apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gohello
  name: gohello
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: gohello
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gohello
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: go-secret
        args:
        - /myapp
        image: iliefa/gohello
        imagePullPolicy: Always
        name: gohello

